import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLang = new BehaviorSubject<string>(localStorage.getItem('language') || 'id');
  lang$ = this.currentLang.asObservable();

  private translations: any = {
    id: {
      home: 'Beranda',
      schedule: 'Jadwal',
      bookings: 'Riwayat',
      profile: 'Profil',
      myToken: 'Tiket Saya',
      accountInfo: 'Informasi Akun',
      personalData: 'Data Pribadi',
      language: 'Bahasa',
      security: 'Keamanan',
      logout: 'Keluar',
      manageProfile: 'Kelola nama dan info kontak',
      manageSecurity: 'Ganti kata sandi & verifikasi',
      selectLanguage: 'Pilih Bahasa',
      greeting: 'Selamat',
      welcome: 'Selamat Datang',
      searchTicket: 'Cari Tiket Bus',
      nextDeparture: 'Keberangkatan Berikutnya',
      origin: 'Asal',
      destination: 'Tujuan',
      travelDate: 'Tanggal Perjalanan',
      passengers: 'Jumlah Penumpang',
      adult: 'Dewasa',
      closestSchedule: 'JADWAL TERDEKAT',
      remainingSeats: 'SISA KURSI',
      status: 'STATUS',
      selectSchedule: 'Pilih Jadwal',
      searchSchedule: 'Cari asal, tujuan, atau unit',
      fastest: 'Tercepat',
      cheapest: 'Termurah',
      seatsAvailable: 'Kursi Tersedia',
      select: 'Pilih',
      noSchedule: 'Tidak ada jadwal ditemukan untuk rute ini.',
      selectSeat: 'Pilih Kursi',
      available: 'Tersedia',
      selected: 'Terpilih',
      occupied: 'Terisi',
      seat: 'Kursi',
      notSelected: 'Belum dipilih',
      confirm: 'Konfirmasi',
      manualTransfer: 'Transfer Bank Manual',
      paymentProgress: 'Progress Pembayaran',
      inputNominal: 'Input Nominal',
      generateVa: 'Buat VA',
      payment: 'Pembayaran',
      finish: 'Selesai',
      awaitingVerification: 'Menunggu Verifikasi Admin',
      customerInfo: 'Informasi Customer',
      customerName: 'Nama Customer',
      bookingNumber: 'Nomor Booking',
      paymentSummary: 'Ringkasan Pembayaran',
      totalBill: 'Total Tagihan',
      inputPaymentAmount: 'Masukkan Nominal Pembayaran',
      continueToTransfer: 'Lanjutkan ke Transfer',
      bankAccountDetail: 'Detail Rekening BNI',
      accountNumber: 'Nomor Rekening',
      bankName: 'Nama Bank',
      accountHolder: 'Nama Pemilik',
      transferAmount: 'Nominal Transfer',
      uniqueCode: 'Kode Unik',
      totalToTransfer: 'Total Harus Ditransfer',
      copyVa: 'Salin Nomor Rekening',
      checkStatus: 'Cek Status Pembayaran',
      createNewVa: 'Ganti Nominal Transfer',
      paymentStatus: 'Status Pembayaran',
      expiryLabel: 'Batas Waktu Transfer',
      paymentImportant: '*PENTING: Mohon transfer tepat hingga 3 digit terakhir agar pesanan dapat diverifikasi secara otomatis.',
      paymentInstruction: 'Gunakan menu Transfer Antar Bank di m-Banking Anda.',
      bookingHistory: 'Riwayat Pemesanan',
      searchHistory: 'Cari riwayat rute...',
      unpaid: 'BELUM DIBAYAR',
      cancelled: 'DIBATALKAN',
      paid: 'LUNAS',
      seatLabel: 'Kursi',
      cancel: 'Batalkan',
      pay: 'Bayar',
      cancelBookingTitle: 'Batalkan Pesanan',
      cancelBookingMessage: 'Apakah Anda yakin ingin membatalkan pesanan ini? Kursi yang dipilih akan tersedia kembali.',
      confirmCancelBtn: 'BATALKAN',
      keepBookingBtn: 'BATAL',
      myBookings: 'Pesanan Saya',
      paymentConfirmed: 'Pembayaran Dikonfirmasi',
      awaitingPayment: 'Menunggu Pembayaran',
      pleaseTransfer: 'Silakan transfer ke rekening berikut:',
      bankAccount: 'Rekening Bank',
      totalTransfer: 'Total Transfer',
      uniqueCodeNote: 'Kode Unik (wajib disertakan)',
      confirmPayment: 'Konfirmasi Sudah Bayar',
      bookingCancelled: 'Pesanan Dibatalkan',
      noBookings: 'Belum ada pesanan.',
      paymentConfirmedToast: 'Pembayaran dikonfirmasi! Admin akan verifikasi segera.',
      viewTicket: 'Lihat e-Tiket',
      uploadProof: 'Upload Bukti Bayar',
      driverPanel: 'Panel Kontrol Driver',
      tripStatus: 'Status Perjalanan',
      boarding: 'Persiapan',
      ongoing: 'Dalam Perjalanan',
      arrived: 'Sampai Tujuan',
      delay: 'Tunda',
      finishTrip: 'Selesaikan',
      vehicleInfo: 'Informasi Armada',
      fuel: 'Bahan Bakar',
      engineTemp: 'Suhu Mesin',
      updateLocation: 'Perbarui Lokasi',
      shiftEndsIn: 'Shift Berakhir Dalam',
      passengerList: 'Daftar Penumpang',
      noPassengers: 'Belum ada penumpang terdaftar.',
      updateStatusSuccess: 'Status perjalanan diperbarui!',
      updateStatusError: 'Gagal memperbarui status perjalanan',
      normal: 'Normal',
      driverLogin: 'Login Driver',
      driverLoginSubtitle: 'Masukkan kredensial Anda untuk mengakses dashboard operasional.',
      driverIdOrEmail: 'ID Driver atau Email',
      password: 'Kata Sandi',
      forgot: 'Lupa?',
      keepLoggedIn: 'Biarkan saya tetap masuk di perangkat ini',
      loginBtn: 'Masuk sebagai Driver',
      backToPassenger: 'Kembali ke Login Penumpang',
      excellence: 'Keunggulan Profesional',
      excellenceSubtitle: 'Mengemban masa depan mobilitas perkotaan yang berkelanjutan dan bebas stres.',
      helpCenter: 'Pusat Bantuan',
      driverSchedule: 'Jadwal Tugas',
      agendaFor: 'Agenda Anda untuk'
    },
    en: {
      home: 'Home',
      schedule: 'Schedule',
      bookings: 'History',
      profile: 'Profile',
      myToken: 'My Tickets',
      accountInfo: 'Account Info',
      personalData: 'Personal Data',
      language: 'Language',
      security: 'Security',
      logout: 'Logout',
      manageProfile: 'Manage name and contact info',
      manageSecurity: 'Change password & verification',
      selectLanguage: 'Select Language',
      greeting: 'Good',
      welcome: 'Welcome',
      searchTicket: 'Search Bus Tickets',
      nextDeparture: 'Next Departure',
      origin: 'Origin',
      destination: 'Destination',
      travelDate: 'Travel Date',
      passengers: 'Passengers',
      adult: 'Adult',
      closestSchedule: 'CLOSEST SCHEDULE',
      remainingSeats: 'REMAINING SEATS',
      status: 'STATUS',
      selectSchedule: 'Select Schedule',
      searchSchedule: 'Search origin, destination, or unit',
      fastest: 'Fastest',
      cheapest: 'Cheapest',
      seatsAvailable: 'Seats Available',
      select: 'Select',
      noSchedule: 'No schedules found for this route.',
      selectSeat: 'Select Seat',
      available: 'Available',
      selected: 'Selected',
      occupied: 'Occupied',
      seat: 'Seat',
      notSelected: 'Not selected',
      confirm: 'Confirm',
      manualTransfer: 'Manual Bank Transfer',
      paymentProgress: 'Payment Progress',
      inputNominal: 'Input Amount',
      generateVa: 'Generate VA',
      payment: 'Payment',
      finish: 'Finished',
      awaitingVerification: 'Awaiting Admin Verification',
      customerInfo: 'Customer Info',
      customerName: 'Customer Name',
      bookingNumber: 'Booking Number',
      paymentSummary: 'Payment Summary',
      totalBill: 'Total Bill',
      inputPaymentAmount: 'Input Payment Amount',
      continueToTransfer: 'Continue to Transfer',
      bankAccountDetail: 'Detail Rekening BNI',
      accountNumber: '1962757389',
      bankName: 'Bank BNI',
      accountHolder: 'Account Holder',
      transferAmount: 'Transfer Amount',
      uniqueCode: 'Unique Code',
      totalToTransfer: 'Total to Transfer',
      copyVa: 'Copy Account Number',
      checkStatus: 'Check Payment Status',
      createNewVa: 'Change Amount',
      paymentStatus: 'Payment Status',
      expiryLabel: 'Transfer Deadline',
      paymentImportant: '*IMPORTANT: Please transfer the exact amount down to the last 3 digits so that your order can be verified automatically.',
      paymentInstruction: 'Use the "Transfer to Other Bank" menu in your m-Banking app.',
      bookingHistory: 'Booking History',
      searchHistory: 'Search routes...',
      unpaid: 'UNPAID',
      cancelled: 'CANCELLED',
      paid: 'PAID',
      seatLabel: 'Seat',
      cancel: 'Cancel',
      pay: 'Pay',
      cancelBookingTitle: 'Cancel Booking',
      cancelBookingMessage: 'Are you sure you want to cancel this booking? The selected seats will become available again.',
      confirmCancelBtn: 'CANCEL BOOKING',
      keepBookingBtn: 'KEEP',
      myBookings: 'My Bookings',
      paymentConfirmed: 'Payment Confirmed',
      awaitingPayment: 'Awaiting Payment',
      pleaseTransfer: 'Please transfer to the following account:',
      bankAccount: 'Bank Account',
      totalTransfer: 'Total to Transfer',
      uniqueCodeNote: 'Unique Code (must be included)',
      confirmPayment: 'I Have Paid',
      bookingCancelled: 'Booking Cancelled',
      noBookings: 'No bookings yet.',
      paymentConfirmedToast: 'Payment confirmed! Admin will verify shortly.',
      viewTicket: 'View e-Ticket',
      uploadProof: 'Upload Payment Proof',
      driverPanel: 'Driver Control Panel',
      tripStatus: 'Trip Status',
      boarding: 'Boarding',
      ongoing: 'On-going',
      arrived: 'Arrived',
      delay: 'Delay',
      finishTrip: 'Finish',
      vehicleInfo: 'Vehicle Info',
      fuel: 'Fuel',
      engineTemp: 'Engine Temp',
      updateLocation: 'Update Location',
      shiftEndsIn: 'Shift Ends In',
      passengerList: 'Passenger List',
      noPassengers: 'No passengers registered yet.',
      updateStatusSuccess: 'Trip status updated!',
      updateStatusError: 'Failed to update trip status',
      normal: 'Normal',
      driverLogin: 'Driver Login',
      driverLoginSubtitle: 'Enter your credentials to access the operational dashboard.',
      driverIdOrEmail: 'Driver ID or Email',
      password: 'Password',
      forgot: 'Forgot?',
      keepLoggedIn: 'Keep me logged in on this device',
      loginBtn: 'Login as Driver',
      backToPassenger: 'Back to Passenger Login',
      excellence: 'Professional Excellence',
      excellenceSubtitle: 'Driving the future of sustainable and stress-free urban mobility.',
      helpCenter: 'Help Center',
      driverSchedule: 'Driver Schedule',
      agendaFor: 'Your Agenda for'
    }
  };

  constructor() {}

  setLanguage(lang: string) {
    localStorage.setItem('language', lang);
    this.currentLang.next(lang);
  }

  get(key: string): string {
    const lang = this.currentLang.value;
    return this.translations[lang][key] || key;
  }

  getCurrentLang() {
    return this.currentLang.value;
  }
}
